### ISSUE TITLE
Are there any ways to prepare own training data?

### ISSUE THREAD

**Issue by ghost** [gogartom/TextMaps#5]
I checked demo.py and it seems also can get raw texts which were marked on the screenshot.

I want to apply this tool for other problems which is not product detection, but it's like extracting web articles with title and content, or stuff like that.

How have you prepared training files? Or are there any tools for annotation?

**Comment by goktasor** [comment]
Hi,

Did you solve the product detection part ?

**Comment by michaeloliverx** [comment]
> I checked demo.py and it seems also can get raw texts which were marked on the screenshot.
> 
> I want to apply this tool for other problems which is not product detection, but it's like extracting web articles with title and content, or stuff like that.
> 
> How have you prepared training files? Or are there any tools for annotation?

Hi did you get any further in this? I would like to do something similar.

**Comment by ghost** [comment]
@michael0liver 
Actually, I've done it by myself.

First, you can save screenshots and dom structure by using ```tools/download_page.js```.
https://github.com/gogartom/TextMaps/blob/master/tools/download_page.js

And then, you should have some URLs as train, valid and test, and can use download_page.js to download them.

Now, you have screenshots and ```dom.json```s. dom.json have dom structures of the target website, and they have the positions of the block contents.

You can annotate what you want to extract, by using two elements:

- the positions of block contents.
- the screenshots

You can transform them into ```Pascal VOC``` format, and it can load from a tool called ```labelImg```.
https://github.com/tzutalin/labelImg

Finally, I created my own model based on TextMaps. I used screenshots as input, and added alpha channel as block positions. The output is a binary classifier that classifies whether the alpha channel is the target position or not.

That's how I annotated the data and created the model, but this is not the official way of TextMaps.

**Comment by michaeloliverx** [comment]
@sugiyamath 
Very good work, thanks for the reply.  May I ask which tools you use to train model tensorflow, scikit-learn? 
I know Python well but I am new to deep/machine learning so I am unsure where to start.  I would like to build something similar to diffbot.com product extraction API.
Which resources did use to learn these technologies ?

**Comment by ghost** [comment]
@michael0liver 
It is not related to the issue, but I'll try to answer.

I used Keras to train it, but recently Keras is merged with TensorFlow 2.0, so we also can use it to use Keras.

I think diffbot.com hasn't published any details of their technologies, and "vision-based web extraction" is a very low-resource topic.

Building a Keras model is an easy part, but defining the features (the inputs of the model) needs to have domain knowledge for the task, so I prefer to search papers to get the domain specific information. If the paper is not free, we can use Sci-Hub to get it free.

If you're new to Keras, "Deep Learning with Python by Francois Chollet" is a good resource, I think.
